name: Health Check

on:
  schedule:
    - cron: '0,30 * * * *'

jobs:
  health_check:
    runs-on: ubuntu-latest
    steps:
      - name: Send health check request
        run: |
          HTTP_STATUS=$(curl -o /dev/null -s -w "%{http_code}" https://fastapi-shop-api-production.up.railway.app/health)
          if [ "$HTTP_STATUS" -ne 200 ]; then
            echo "Status code $HTTP_STATUS"
            exit 1
          else
            echo "Status code $HTTP_STATUS"
          fi